// Valid data structure for Importance-Performance Analysis (IPA)
// Each data point represents an attribute with its importance and performance scores.

export const dummyIPAData = [
  { attribute: 'Product Quality', importance: 8.5, performance: 7.3 },
  { attribute: 'Customer Service', importance: 9.2, performance: 6.1 },
  { attribute: 'Delivery Speed', importance: 7.0, performance: 8.5 },
  { attribute: 'Website Usability', importance: 6.8, performance: 7.9 },
  { attribute: 'Price Competitiveness', importance: 8.0, performance: 8.2 },
  { attribute: 'Technical Support', importance: 7.5, performance: 5.8 },
  { attribute: 'Marketing Effectiveness', importance: 6.0, performance: 6.9 },
  { attribute: 'Brand Reputation', importance: 9.0, performance: 8.1 },
  { attribute: 'Innovation', importance: 7.8, performance: 7.0 },
  { attribute: 'Employee Knowledge', importance: 8.2, performance: 6.7 },
  { attribute: 'Payment Options', importance: 6.5, performance: 8.5 },
  { attribute: 'Return Policy', importance: 7.2, performance: 7.4 },
  { attribute: 'Product Variety', importance: 6.0, performance: 6.2 },
  { attribute: 'Loyalty Program', importance: 5.5, performance: 5.9 },
  { attribute: 'Social Media Presence', importance: 6.8, performance: 7.3 },
  { attribute: 'Sales Team Effectiveness', importance: 7.7, performance: 8.0 },
  { attribute: 'Training Programs', importance: 7.3, performance: 6.4 },
  { attribute: 'Data Security', importance: 9.5, performance: 8.8 },
  { attribute: 'Ease of Use', importance: 8.8, performance: 8.0 },
  { attribute: 'Reliability', importance: 9.1, performance: 8.3 },
  { attribute: 'Customization', importance: 6.2, performance: 7.0 },
  { attribute: 'After-Sales Service', importance: 8.3, performance: 7.5 },
  { attribute: 'Online Resources', importance: 6.7, performance: 7.4 },
  { attribute: 'Community Engagement', importance: 5.8, performance: 6.1 },
  { attribute: 'Sustainability', importance: 7.6, performance: 7.1 },
  { attribute: 'User Experience', importance: 8.9, performance: 8.4 },
  { attribute: 'Accessibility', importance: 7.9, performance: 8.3 },
  { attribute: 'Communication', importance: 8.4, performance: 7.2 },
  { attribute: 'Flexibility', importance: 7.1, performance: 6.5 },
  { attribute: 'Efficiency', importance: 8.7, performance: 8.1 },
  { attribute: 'Responsiveness', importance: 9.3, performance: 8.6 },
  { attribute: 'Innovation Speed', importance: 7.4, performance: 7.2 },
  { attribute: 'Resource Availability', importance: 6.9, performance: 6.8 },
  { attribute: 'Team Collaboration', importance: 8.1, performance: 7.8 },
  { attribute: 'Project Management', importance: 7.8, performance: 7.0 },
  { attribute: 'Quality Control', importance: 9.4, performance: 8.9 },
  { attribute: 'Risk Management', importance: 8.6, performance: 8.0 },
  { attribute: 'Strategic Planning', importance: 8.2, performance: 7.5 },
  { attribute: 'Financial Stability', importance: 9.0, performance: 8.2 },
  { attribute: 'Market Analysis', importance: 7.5, performance: 7.1 },
  { attribute: 'Customer Feedback', importance: 8.3, performance: 7.9 },
  { attribute: 'Employee Morale', importance: 7.7, performance: 7.3 },
  { attribute: 'Process Optimization', importance: 7.9, performance: 7.5 },
  { attribute: 'Knowledge Sharing', importance: 7.2, performance: 6.9 },
  { attribute: 'Performance Monitoring', importance: 8.0, performance: 7.6 },
  { attribute: 'Resource Allocation', importance: 7.6, performance: 7.2 },
  { attribute: 'Supplier Relationships', importance: 7.4, performance: 7.0 },
  { attribute: 'Technology Integration', importance: 8.5, performance: 8.1 },
  { attribute: 'Training Effectiveness', importance: 6.8, performance: 6.5 },
  { attribute: 'Workplace Safety', importance: 9.2, performance: 8.7 },
  { attribute: 'Environmental Impact', importance: 7.0, performance: 6.8 },
];

// Now use this dummyIPAData with your React/D3.js code.
