SET check_function_bodies = false;

-- Additional users for diverse answer sheets
INSERT INTO public.users (email, password, name) VALUES ('mahasiswa1@univ.ac.id', 'password', 'Ahmad Rizki Pratama');
INSERT INTO public.users (email, password, name) VALUES ('mahasiswa2@univ.ac.id', 'password', 'Sari Dewi Putri');
INSERT INTO public.users (email, password, name) VALUES ('mahasiswa3@univ.ac.id', 'password', 'Budi Santoso');
INSERT INTO public.users (email, password, name) VALUES ('mahasiswa4@univ.ac.id', 'password', 'Dina Rahayu');
INSERT INTO public.users (email, password, name) VALUES ('mahasiswa5@univ.ac.id', 'password', 'Eko Nugroho');
INSERT INTO public.users (email, password, name) VALUES ('mahasiswa6@univ.ac.id', 'password', 'Fitri Handayani');
INSERT INTO public.users (email, password, name) VALUES ('mahasiswa7@univ.ac.id', 'password', 'Gunawan Saputra');
INSERT INTO public.users (email, password, name) VALUES ('mahasiswa8@univ.ac.id', 'password', 'Hesti Wulandari');
INSERT INTO public.users (email, password, name) VALUES ('alumni1@univ.ac.id', 'password', 'Indra Kusuma');
INSERT INTO public.users (email, password, name) VALUES ('alumni2@univ.ac.id', 'password', 'Joko Widodo');

-- 10 IPA Questions related to college academic, research, graduation career
INSERT INTO public.questions (topic, content, caption, option, question_type_id, form_id, "order", required) VALUES 
(NULL, 'Kualitas Dosen dalam Mengajar', NULL, '{"type": "Importance Performance", "importance": [{"id": "imp1-1", "label": "Sangat Tidak Penting", "value": 1}, {"id": "imp1-2", "label": "Tidak Penting", "value": 2}, {"id": "imp1-3", "label": "Cukup Penting", "value": 3}, {"id": "imp1-4", "label": "Penting", "value": 4}, {"id": "imp1-5", "label": "Sangat Penting", "value": 5}], "performance": [{"id": "perf1-1", "label": "Sangat Kurang", "value": 1}, {"id": "perf1-2", "label": "Kurang", "value": 2}, {"id": "perf1-3", "label": "Cukup", "value": 3}, {"id": "perf1-4", "label": "Baik", "value": 4}, {"id": "perf1-5", "label": "Sangat Baik", "value": 5}], "importanceQuestion": "Seberapa penting kualitas dosen dalam mengajar bagi anda?", "performanceQuestion": "Bagaimana performa kualitas dosen dalam mengajar menurut anda?"}', 2, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 101, true),

(NULL, 'Fasilitas Laboratorium dan Perpustakaan', NULL, '{"type": "Importance Performance", "importance": [{"id": "imp2-1", "label": "Sangat Tidak Penting", "value": 1}, {"id": "imp2-2", "label": "Tidak Penting", "value": 2}, {"id": "imp2-3", "label": "Cukup Penting", "value": 3}, {"id": "imp2-4", "label": "Penting", "value": 4}, {"id": "imp2-5", "label": "Sangat Penting", "value": 5}], "performance": [{"id": "perf2-1", "label": "Sangat Kurang", "value": 1}, {"id": "perf2-2", "label": "Kurang", "value": 2}, {"id": "perf2-3", "label": "Cukup", "value": 3}, {"id": "perf2-4", "label": "Baik", "value": 4}, {"id": "perf2-5", "label": "Sangat Baik", "value": 5}], "importanceQuestion": "Seberapa penting fasilitas laboratorium dan perpustakaan bagi anda?", "performanceQuestion": "Bagaimana kondisi fasilitas laboratorium dan perpustakaan menurut anda?"}', 2, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 102, true),

(NULL, 'Bimbingan Akademik dan Konseling', NULL, '{"type": "Importance Performance", "importance": [{"id": "imp3-1", "label": "Sangat Tidak Penting", "value": 1}, {"id": "imp3-2", "label": "Tidak Penting", "value": 2}, {"id": "imp3-3", "label": "Cukup Penting", "value": 3}, {"id": "imp3-4", "label": "Penting", "value": 4}, {"id": "imp3-5", "label": "Sangat Penting", "value": 5}], "performance": [{"id": "perf3-1", "label": "Sangat Kurang", "value": 1}, {"id": "perf3-2", "label": "Kurang", "value": 2}, {"id": "perf3-3", "label": "Cukup", "value": 3}, {"id": "perf3-4", "label": "Baik", "value": 4}, {"id": "perf3-5", "label": "Sangat Baik", "value": 5}], "importanceQuestion": "Seberapa penting bimbingan akademik dan konseling bagi anda?", "performanceQuestion": "Bagaimana kualitas bimbingan akademik dan konseling yang anda terima?"}', 2, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 103, true),

(NULL, 'Kurikulum dan Materi Pembelajaran', NULL, '{"type": "Importance Performance", "importance": [{"id": "imp4-1", "label": "Sangat Tidak Penting", "value": 1}, {"id": "imp4-2", "label": "Tidak Penting", "value": 2}, {"id": "imp4-3", "label": "Cukup Penting", "value": 3}, {"id": "imp4-4", "label": "Penting", "value": 4}, {"id": "imp4-5", "label": "Sangat Penting", "value": 5}], "performance": [{"id": "perf4-1", "label": "Sangat Kurang", "value": 1}, {"id": "perf4-2", "label": "Kurang", "value": 2}, {"id": "perf4-3", "label": "Cukup", "value": 3}, {"id": "perf4-4", "label": "Baik", "value": 4}, {"id": "perf4-5", "label": "Sangat Baik", "value": 5}], "importanceQuestion": "Seberapa penting kurikulum dan materi pembelajaran bagi anda?", "performanceQuestion": "Bagaimana relevansi kurikulum dan materi pembelajaran menurut anda?"}', 2, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 104, true),

(NULL, 'Penelitian dan Publikasi Ilmiah', NULL, '{"type": "Importance Performance", "importance": [{"id": "imp5-1", "label": "Sangat Tidak Penting", "value": 1}, {"id": "imp5-2", "label": "Tidak Penting", "value": 2}, {"id": "imp5-3", "label": "Cukup Penting", "value": 3}, {"id": "imp5-4", "label": "Penting", "value": 4}, {"id": "imp5-5", "label": "Sangat Penting", "value": 5}], "performance": [{"id": "perf5-1", "label": "Sangat Kurang", "value": 1}, {"id": "perf5-2", "label": "Kurang", "value": 2}, {"id": "perf5-3", "label": "Cukup", "value": 3}, {"id": "perf5-4", "label": "Baik", "value": 4}, {"id": "perf5-5", "label": "Sangat Baik", "value": 5}], "importanceQuestion": "Seberapa penting program penelitian dan publikasi ilmiah bagi anda?", "performanceQuestion": "Bagaimana dukungan untuk penelitian dan publikasi ilmiah yang anda terima?"}', 2, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 105, true),

(NULL, 'Kesiapan Kerja dan Career Development', NULL, '{"type": "Importance Performance", "importance": [{"id": "imp6-1", "label": "Sangat Tidak Penting", "value": 1}, {"id": "imp6-2", "label": "Tidak Penting", "value": 2}, {"id": "imp6-3", "label": "Cukup Penting", "value": 3}, {"id": "imp6-4", "label": "Penting", "value": 4}, {"id": "imp6-5", "label": "Sangat Penting", "value": 5}], "performance": [{"id": "perf6-1", "label": "Sangat Kurang", "value": 1}, {"id": "perf6-2", "label": "Kurang", "value": 2}, {"id": "perf6-3", "label": "Cukup", "value": 3}, {"id": "perf6-4", "label": "Baik", "value": 4}, {"id": "perf6-5", "label": "Sangat Baik", "value": 5}], "importanceQuestion": "Seberapa penting program kesiapan kerja dan career development bagi anda?", "performanceQuestion": "Bagaimana efektivitas program kesiapan kerja dan career development menurut anda?"}', 2, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 106, true),

(NULL, 'Praktikum dan Pengalaman Lapangan', NULL, '{"type": "Importance Performance", "importance": [{"id": "imp7-1", "label": "Sangat Tidak Penting", "value": 1}, {"id": "imp7-2", "label": "Tidak Penting", "value": 2}, {"id": "imp7-3", "label": "Cukup Penting", "value": 3}, {"id": "imp7-4", "label": "Penting", "value": 4}, {"id": "imp7-5", "label": "Sangat Penting", "value": 5}], "performance": [{"id": "perf7-1", "label": "Sangat Kurang", "value": 1}, {"id": "perf7-2", "label": "Kurang", "value": 2}, {"id": "perf7-3", "label": "Cukup", "value": 3}, {"id": "perf7-4", "label": "Baik", "value": 4}, {"id": "perf7-5", "label": "Sangat Baik", "value": 5}], "importanceQuestion": "Seberapa penting kegiatan praktikum dan pengalaman lapangan bagi anda?", "performanceQuestion": "Bagaimana kualitas kegiatan praktikum dan pengalaman lapangan yang anda dapatkan?"}', 2, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 107, true),

(NULL, 'Teknologi dan E-Learning', NULL, '{"type": "Importance Performance", "importance": [{"id": "imp8-1", "label": "Sangat Tidak Penting", "value": 1}, {"id": "imp8-2", "label": "Tidak Penting", "value": 2}, {"id": "imp8-3", "label": "Cukup Penting", "value": 3}, {"id": "imp8-4", "label": "Penting", "value": 4}, {"id": "imp8-5", "label": "Sangat Penting", "value": 5}], "performance": [{"id": "perf8-1", "label": "Sangat Kurang", "value": 1}, {"id": "perf8-2", "label": "Kurang", "value": 2}, {"id": "perf8-3", "label": "Cukup", "value": 3}, {"id": "perf8-4", "label": "Baik", "value": 4}, {"id": "perf8-5", "label": "Sangat Baik", "value": 5}], "importanceQuestion": "Seberapa penting teknologi dan platform e-learning bagi anda?", "performanceQuestion": "Bagaimana kualitas teknologi dan platform e-learning yang disediakan?"}', 2, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 108, true),

(NULL, 'Organisasi Kemahasiswaan dan Soft Skills', NULL, '{"type": "Importance Performance", "importance": [{"id": "imp9-1", "label": "Sangat Tidak Penting", "value": 1}, {"id": "imp9-2", "label": "Tidak Penting", "value": 2}, {"id": "imp9-3", "label": "Cukup Penting", "value": 3}, {"id": "imp9-4", "label": "Penting", "value": 4}, {"id": "imp9-5", "label": "Sangat Penting", "value": 5}], "performance": [{"id": "perf9-1", "label": "Sangat Kurang", "value": 1}, {"id": "perf9-2", "label": "Kurang", "value": 2}, {"id": "perf9-3", "label": "Cukup", "value": 3}, {"id": "perf9-4", "label": "Baik", "value": 4}, {"id": "perf9-5", "label": "Sangat Baik", "value": 5}], "importanceQuestion": "Seberapa penting organisasi kemahasiswaan dalam pengembangan soft skills bagi anda?", "performanceQuestion": "Bagaimana kontribusi organisasi kemahasiswaan dalam pengembangan soft skills anda?"}', 2, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 109, true),

(NULL, 'Alumni Network dan Job Placement', NULL, '{"type": "Importance Performance", "importance": [{"id": "imp10-1", "label": "Sangat Tidak Penting", "value": 1}, {"id": "imp10-2", "label": "Tidak Penting", "value": 2}, {"id": "imp10-3", "label": "Cukup Penting", "value": 3}, {"id": "imp10-4", "label": "Penting", "value": 4}, {"id": "imp10-5", "label": "Sangat Penting", "value": 5}], "performance": [{"id": "perf10-1", "label": "Sangat Kurang", "value": 1}, {"id": "perf10-2", "label": "Kurang", "value": 2}, {"id": "perf10-3", "label": "Cukup", "value": 3}, {"id": "perf10-4", "label": "Baik", "value": 4}, {"id": "perf10-5", "label": "Sangat Baik", "value": 5}], "importanceQuestion": "Seberapa penting jaringan alumni dan job placement bagi anda?", "performanceQuestion": "Bagaimana efektivitas jaringan alumni dan job placement menurut anda?"}', 2, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 110, true);

-- 10 Ratio/Multiple Questions related to college academic, research, graduation career
INSERT INTO public.questions (topic, content, caption, option, question_type_id, form_id, "order", required) VALUES 
(NULL, 'Berapa lama waktu ideal untuk menyelesaikan tugas akhir/skripsi?', NULL, '{"type": "Ratio", "option": [{"id": "ratio1-1", "label": "6 bulan", "value": 1}, {"id": "ratio1-2", "label": "1 tahun", "value": 2}, {"id": "ratio1-3", "label": "1.5 tahun", "value": 3}, {"id": "ratio1-4", "label": "2 tahun", "value": 4}, {"id": "ratio1-5", "label": "Lebih dari 2 tahun", "value": 5}]}', 4, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 201, true),

(NULL, 'Seberapa sering anda mengakses perpustakaan untuk keperluan akademik?', NULL, '{"type": "Ratio", "option": [{"id": "ratio2-1", "label": "Tidak pernah", "value": 1}, {"id": "ratio2-2", "label": "Jarang (1-2 kali/bulan)", "value": 2}, {"id": "ratio2-3", "label": "Cukup sering (1-2 kali/minggu)", "value": 3}, {"id": "ratio2-4", "label": "Sering (3-4 kali/minggu)", "value": 4}, {"id": "ratio2-5", "label": "Sangat sering (setiap hari)", "value": 5}]}', 4, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 202, true),

(NULL, 'Berapa banyak publikasi ilmiah yang telah anda hasilkan selama kuliah?', NULL, '{"type": "Ratio", "option": [{"id": "ratio3-1", "label": "Belum ada", "value": 1}, {"id": "ratio3-2", "label": "1-2 publikasi", "value": 2}, {"id": "ratio3-3", "label": "3-5 publikasi", "value": 3}, {"id": "ratio3-4", "label": "6-10 publikasi", "value": 4}, {"id": "ratio3-5", "label": "Lebih dari 10 publikasi", "value": 5}]}', 4, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 203, true),

(NULL, 'Apa program studi yang anda ambil?', NULL, '{"type": "Multiple", "option": [{"id": "multiple1-1", "label": "Teknik Informatika", "value": 1}, {"id": "multiple1-2", "label": "Sistem Informasi", "value": 2}, {"id": "multiple1-3", "label": "Teknik Elektro", "value": 3}, {"id": "multiple1-4", "label": "Manajemen", "value": 4}, {"id": "multiple1-5", "label": "Akuntansi", "value": 5}, {"id": "multiple1-6", "label": "Lainnya", "value": 6}]}', 5, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 204, true),

(NULL, 'Bidang penelitian apa yang paling menarik bagi anda?', NULL, '{"type": "Multiple", "option": [{"id": "multiple2-1", "label": "Artificial Intelligence", "value": 1}, {"id": "multiple2-2", "label": "Cybersecurity", "value": 2}, {"id": "multiple2-3", "label": "Data Science", "value": 3}, {"id": "multiple2-4", "label": "Software Engineering", "value": 4}, {"id": "multiple2-5", "label": "Internet of Things", "value": 5}, {"id": "multiple2-6", "label": "Mobile Development", "value": 6}]}', 5, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 205, true),

(NULL, 'Setelah lulus, apa rencana karir anda?', NULL, '{"type": "Multiple", "option": [{"id": "multiple3-1", "label": "Bekerja di perusahaan teknologi", "value": 1}, {"id": "multiple3-2", "label": "Melanjutkan studi S2", "value": 2}, {"id": "multiple3-3", "label": "Berwirausaha/startup", "value": 3}, {"id": "multiple3-4", "label": "Bekerja sebagai freelancer", "value": 4}, {"id": "multiple3-5", "label": "Menjadi dosen/peneliti", "value": 5}, {"id": "multiple3-6", "label": "Belum tahu", "value": 6}]}', 5, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 206, true),

(NULL, 'Metode pembelajaran mana yang paling efektif untuk anda?', NULL, '{"type": "Multiple", "option": [{"id": "multiple4-1", "label": "Tatap muka di kelas", "value": 1}, {"id": "multiple4-2", "label": "Online learning", "value": 2}, {"id": "multiple4-3", "label": "Blended learning", "value": 3}, {"id": "multiple4-4", "label": "Praktikum laboratorium", "value": 4}, {"id": "multiple4-5", "label": "Project-based learning", "value": 5}, {"id": "multiple4-6", "label": "Studi kasus", "value": 6}]}', 5, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 207, true),

(NULL, 'Seberapa puas anda dengan layanan administrasi akademik?', NULL, '{"type": "Ratio", "option": [{"id": "ratio4-1", "label": "Sangat tidak puas", "value": 1}, {"id": "ratio4-2", "label": "Tidak puas", "value": 2}, {"id": "ratio4-3", "label": "Cukup puas", "value": 3}, {"id": "ratio4-4", "label": "Puas", "value": 4}, {"id": "ratio4-5", "label": "Sangat puas", "value": 5}]}', 4, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 208, true),

(NULL, 'Skill apa yang paling ingin anda kembangkan?', NULL, '{"type": "Multiple", "option": [{"id": "multiple5-1", "label": "Programming", "value": 1}, {"id": "multiple5-2", "label": "Leadership", "value": 2}, {"id": "multiple5-3", "label": "Communication", "value": 3}, {"id": "multiple5-4", "label": "Problem Solving", "value": 4}, {"id": "multiple5-5", "label": "Project Management", "value": 5}, {"id": "multiple5-6", "label": "Research & Analysis", "value": 6}]}', 5, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 209, true),

(NULL, 'Seberapa sering anda berpartisipasi dalam kegiatan akademik di luar kelas?', NULL, '{"type": "Ratio", "option": [{"id": "ratio5-1", "label": "Tidak pernah", "value": 1}, {"id": "ratio5-2", "label": "Jarang", "value": 2}, {"id": "ratio5-3", "label": "Kadang-kadang", "value": 3}, {"id": "ratio5-4", "label": "Sering", "value": 4}, {"id": "ratio5-5", "label": "Selalu", "value": 5}]}', 4, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 210, true);

-- Personal Information Questions
INSERT INTO public.questions (topic, content, caption, option, question_type_id, form_id, "order", required) VALUES 
(NULL, 'Nama Lengkap', NULL, '{"type": "Name", "option": []}', 3, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 301, true),
(NULL, 'Email', NULL, '{"type": "Email"}', 3, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 302, true),
(NULL, 'Nomor Induk Mahasiswa (NIM)', NULL, '{"type": "Number"}', 3, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 303, true),
(NULL, 'Angkatan', NULL, '{"type": "Number"}', 3, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 304, true),
(NULL, 'Alamat', NULL, '{"type": "Address"}', 3, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 305, false),
(NULL, 'Nomor Telepon', NULL, '{"type": "Phone"}', 3, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 306, false),
(NULL, 'Jenis Kelamin', NULL, '{"type": "Multiple", "option": [{"id": "gender-1", "label": "Laki-laki", "value": 1}, {"id": "gender-2", "label": "Perempuan", "value": 2}]}', 5, 'e85960b4-4d78-4d9c-bdc2-ae263ff28d10', 307, true);
