-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."answer_sheets" add column "recorded" boolean
--  not null default 'false';
